### ISSUE TITLE
Installation failures with `cargo` 1.79.0

### ISSUE THREAD

**Issue by metaleap** [raviqqe/schemat#142]
Hiya, curious to try out `schemat`!

Just for that, I installed `rust` to have `cargo` on my system.

With your README's instruction to `cargo +nightly install schemat`, the following error was given:

```
error: no such command: `+nightly`

        Cargo does not handle `+toolchain` directives.
        Did you mean to invoke `cargo` through `rustup` instead?
```

What a question! :grin: 

So I tried `cargo install schemat` (outdated `schemat v0.2.9` from February, so I won't try again), but just FYI that threw compile error `E0554` for `bumpalo` and `mfmt` libs (maybe just because outdated though).

**Comment by raviqqe** [comment]
So as the error message says, you need to install Rust via `rustup` rather than using the one on your OS or any platform. https://rustup.rs/

The `E0554` is because you are using the stable Rust instead of the nightly one.

**Comment by metaleap** [comment]
Ah I see! Hm, might wanna update your README because Schemers aren't always (or usually, lol) also Rusters  :grin:

All good tho, thanks @raviqqe
